#ifndef FONTS_CUSTOM_H
#define FONTS_CUSTOM_H

#include "lvgl.h"

/* Montserrat Bold — generated by fonts/generate.sh
 * ASCII (0x20-0x7E) + Nerd Font Logos (0xF300-0xF381), 4bpp */
LV_FONT_DECLARE(lv_font_montserrat_bold_14);
LV_FONT_DECLARE(lv_font_montserrat_bold_16);
LV_FONT_DECLARE(lv_font_montserrat_bold_20);
LV_FONT_DECLARE(lv_font_montserrat_bold_24);
LV_FONT_DECLARE(lv_font_montserrat_bold_28);
LV_FONT_DECLARE(lv_font_montserrat_bold_36);
LV_FONT_DECLARE(lv_font_montserrat_bold_48);

#endif /* FONTS_CUSTOM_H */
